backend:
  name: github
  repo: antonbwskak/allintime
  branch: main

media_folder: "media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "watches"
    label: "Ure"
    folder: "content/watches"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Brand, name: brand, widget: string}
      - {label: Model, name: model, widget: string}
      - {label: Slug, name: slug, widget: string}
      - {label: Reference, name: reference, widget: string, required: false}
      - {label: Year, name: year, widget: string, required: false}
      - {label: Condition, name: condition, widget: string, required: false}
      - {label: Description, name: description, widget: text}
      - {label: Price (DKK), name: price_dkk, widget: number, required: false}
      - {label: Status, name: status, widget: select, options: ["available", "sold"]}
      - {label: Featured, name: featured, widget: boolean, default: false}
      - {label: Tilbehør, name: set, widget: string, required: false}
      - {label: Images, name: images, widget: list}
